sudo: true
dist: trusty
env:
  global:
  - DOCKER_USERNAME=matthewberryman
  - secure: Yz/4NaVTq5UHzws0hojJ6A/kdvBmBheI5HCNd29LBI9jbhYO9FWDKKiAOMTtPK7v9LxPIvw+UsRew45JbWIliTLS5Fzs0TDV0uMuwfWiXN5nx8g81+If1ropiiI5f4oFjDfJDZuOUCnZaJuz+dH9lht8cY2K3fuWPyMpq6sYg3OVcmWHOhPrc5+0lOzGinTwTSFraJnWUyYVJ/Gc+s1U2G4C4WN+Tn+YXIG4uaCdUUe8dvYbtNd8CyWmZr+gguh9TejMnoELCzoSwUXWJiPiVErEvQ/scOx+Nhak+rCCuV9wk9fPNRazdBOZixa6gYj1nWY4PQS6IE/V1d4RBfa8UREZYK7zG6mvF+O3gJGFpIM7DQ1CpWmTwHoAOpNcdcHEekd6ciTLDEKI1y9JHnHfUMnGoHwfShaempoHKJnaiJc2gOSD4Bg0PVBXjYCbX9QDqwoJDGyt4rX5/mT3Ke6GV6fGx9TUSJKWzlOv4/IEhEBBXx8goaqAHECmLIZlFdCvX0UJRtaE5ALQj7pFTeInuGTRNU4T5wMxXOPH12zklsdqJ7+yxR9ld4Bsw3x0DfelcQLUbhnGcrMXPfLPC4qY8BAE+lgGFdWmFnHBSEarBo/P/WW7xZhsFRDmVmJ+tfuv2s7cCLu+CYBeoQN+5A8bulT+K9QXx5/6yxLcmYV5oT4=
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_USERNAME/mongodb .
    - docker push $DOCKER_USERNAME/mongodb
